
project:
  type: website
  output-dir: docs

website:
  title: "ProCoReS"
  favicon: imgs/logo/1.png
  navbar:
    logo: imgs/logo/2.png
    title: false
    left:
      - href: index.qmd
        text: Home
      - href: team.qmd
        text: Equipe
      - href: works.qmd
        text: Trabalhos

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



