
project:
  type: website
  output-dir: docs

website:
  title: "ProCoReS - Pesquisas em Redes Sociais"
  navbar:
    logo: imgs/logo/1.png
    left:
      - href: index.qmd
        text: ""
      - href: team.qmd
        text: Equipe
      - href: works.qmd
        text: Trabalhos
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



